###Delete a user
DELETE http://localhost:3003/api/users/61498b3f3ca2c5fbfdf4cc62

###Delete a blog
DELETE http://localhost:3003/api/blogs/62023b9061c892346bf4ad7d
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOiI2MjAwZDMxYTY2MjZkNGJhMWI3NmU4NGUiLCJpYXQiOjE2NDQzMTM0MzQsImV4cCI6MTY0NDMxNzAzNH0.1fkHJclEnDwSyptWLekfxJVQBvmtP232XGCY5BPWjFY