###Delete a user
DELETE http://localhost:3003/api/users/61498b3f3ca2c5fbfdf4cc62

###Delete a blog
DELETE http://localhost:3003/api/blogs/614b5cc103a491b78fd49421
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOiI2MTQ5OGIxNzNjYTJjNWZiZmRmNGNjNjAiLCJpYXQiOjE2MzIzMjY2MDgsImV4cCI6MTYzMjMzMDIwOH0.F7AcG3_XrIgOHoB8eJICJ7ppvcDU3JHGxVwcEe24xWQ