### create new blog post
POST http://localhost:3003/api/blogs
content-type: application/json

{
    "title": "test userId Fullstackopen part 5",
    "author": "mluukkai",
    "url": "https://fullstackopen.com/en/part5",
    "likes": 18,
    "userId": "61498b3f3ca2c5fbfdf4cc62"
}

### create new user
POST http://localhost:3003/api/users
content-type: application/json

{
    "username": "admin",
    "password": "admin123",
    "name": "root",
    "blogs": []
}

### login
POST http://localhost:3003/api/login
content-type: application/json

{
    "username": "admin",
    "password": "admin123"
}