### create new blog post
POST http://localhost:3003/api/blogs
content-type: application/json

{
    "title": "test userId Fullstackopen part 5",
    "author": "mluukkai",
    "url": "https://fullstackopen.com/en/part5",
    "likes": 18,
    "userId": "61498b3f3ca2c5fbfdf4cc62"
}

### create new blog post with auth token
POST http://localhost:3003/api/blogs
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOiI2MTQ5OGIxNzNjYTJjNWZiZmRmNGNjNjAiLCJpYXQiOjE2MzIyNDY3MDksImV4cCI6MTYzMjI1MDMwOX0.Wd5iB3N-lYgpoLIIhQEzdF0JoZsU1fv7JIP5lDWC8P0
//comment out Authorization header to test error handling when token is invalid
{
    "title": "Test create blog with token",
    "author": "test",
    "url": "https://fullstackopen.com/en/part6",
    "likes": 21
}

### create new user
POST http://localhost:3003/api/users
content-type: application/json

{
    "username": "admin",
    "password": "admin123",
    "name": "root",
    "blogs": []
}

### login
POST http://localhost:3003/api/login
content-type: application/json

{
    "username": "admin",
    "password": "admin123"
}